##### Service(Loadbalancer or Ingress) ########
apiVersion: v1
kind: Service
metadata:
  name: car-rental-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: car-rental-app