apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  #echo -n '' | base64 encode values
  oauth2ClientId: MGI1MDA1MjQtOGZkZi00MmNmLTlhNTUtZDFkMDY5YTg1NTE3
  oauth2Secret: YTJhYTEwYUNyTDNIckhaU0tRb2tmcXhuUjdLTmNRRGtuajBvTmkzY09YYjh6bVVGb0Fram5vdk9q
  oauth2JwtKeyValue: MTIzQCEj