#https://stackoverflow.com/questions/45681780/how-to-initialize-mysql-container-when-created-on-kubernetes
#https://hub.docker.com/_/mysql/
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE USERS(
          ID BIGINT NOT NULL AUTO_INCREMENT,
          USER_NAME VARCHAR(50) NOT NULL,
          PASSWORD VARCHAR(200) NOT NULL,
          FIRST_NAME VARCHAR(25),
          LAST_NAME VARCHAR(25),
          EMAIL VARCHAR(255) NOT NULL,
          PHONE VARCHAR(20) NOT NULL,
          DRIVING_LICENCE_NO VARCHAR(255) NOT NULL,

          CREATED_BY VARCHAR(50) NOT NULL,
          CREATED_DATE DATETIME NOT NULL,
          MODIFIED_BY VARCHAR(50) NOT NULL,
          MODIFIED_DATE DATETIME NOT NULL,
          VERSION BIGINT NOT NULL,
          PRIMARY KEY (ID),
          CONSTRAINT UC_USERNAME UNIQUE(USER_NAME)
    );

    CREATE TABLE CAR (
    	ID BIGINT NOT NULL AUTO_INCREMENT,
    	CAR_BRAND VARCHAR(20) NOT NULL, -- BMW, TOYOTA, ...
    	CAR_MODEL VARCHAR(20) NOT NULL, -- BMW 650, ...
    	CAR_TYPE VARCHAR(20) NOT NULL, -- SUV, VAN, FULL SIZE, ....
    	COLOR VARCHAR(20) NOT NULL,
        CAPACITY TINYINT NOT NULL, -- 5, 7, 8 , 2
        PLATE_NUMBER VARCHAR(12) NOT NULL,
    	MILEAGE INT NOT NULL,

    	CREATED_BY VARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        MODIFIED_BY VARCHAR(50) NOT NULL,
        MODIFIED_DATE DATETIME NOT NULL,
        VERSION BIGINT NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT UC_CAR_PLATE_NUMBER UNIQUE(PLATE_NUMBER)
    );

    CREATE TABLE CAR_PRICE(
       ID BIGINT NOT NULL AUTO_INCREMENT,
       CAR_ID BIGINT NOT NULL,
       DATE_OF_YEAR DATE NOT NULL, -- 2020-10-21
       PRICE DECIMAL(6,2) NOT NULL, -- 328
       IS_AVAILABLE BIT NOT NULL, -- 0/1

       CREATED_BY VARCHAR(50) NOT NULL,
       CREATED_DATE DATETIME NOT NULL,
       MODIFIED_BY VARCHAR(50) NOT NULL,
       MODIFIED_DATE DATETIME NOT NULL,
       VERSION BIGINT NOT NULL,
       PRIMARY KEY (ID),
       CONSTRAINT UC_CAR_DAY_PRICE UNIQUE(CAR_ID, DATE_OF_YEAR),
       CONSTRAINT FK_CAR_PRICE_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
    );

    CREATE TABLE RESERVATION_ORDER(
    	ID BIGINT NOT NULL AUTO_INCREMENT,
    	CAR_ID BIGINT NOT NULL,
    	RESERVED_BY BIGINT NOT NULL, -- customer ID
    	RESERVED_DATE DATETIME NOT NULL,
    	PICK_UP_DATE DATE NOT NULL,
    	PICK_UP_TIME TIME NOT NULL,
    	RETURN_DATE DATE NOT NULL,
    	RETURN_TIME TIME NOT NULL,
    	TOTAL_AMOUNT DECIMAL(12,2) NOT NULL, -- SUM(price of every day of the rent range)
        RESERVE_STATUS TINYINT NOT NULL, -- Confirmed, Cancelled, Completed

    	CREATED_BY VARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        MODIFIED_BY VARCHAR(50) NOT NULL,
        MODIFIED_DATE DATETIME NOT NULL,
        VERSION BIGINT NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT FK_RESERVATION_ORDER_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID),
        CONSTRAINT FK_RESERVATION_ORDER_USERS FOREIGN KEY (RESERVED_BY) REFERENCES USERS(ID)
    );

    INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DRIVING_LICENCE_NO, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    VALUES ('customerA', '$2a$10$icV.3JxkVcL2VuX4bXC41OHA.Z2cZ3UEdhR7qXdV0cb8CEGfcGOYy', 'CUSA_First', 'CUSA_Last', 'customerA@plc.com', '123456789', '21028219910101888X', 'Admin', NOW(), 'Admin', NOW(), 0);

    INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DRIVING_LICENCE_NO, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    VALUES ('customerB', '$2a$10$ZFvRIl7bn37EDAPSse8wJetGhgie2mpyD24mUFhvPODWPzoKJqnzW', 'CUSB_First', 'CUSB_Last', 'customerB@plc.com', '234567890', '21028219950101666X', 'Admin', NOW(), 'Admin', NOW(), 0);


    INSERT INTO CAR(CAR_BRAND, CAR_MODEL, CAR_TYPE, COLOR, CAPACITY, PLATE_NUMBER, MILEAGE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION) VALUES
    ('BMW', 'BMW 650', 'LCAR', 'WHITE', 5, 'YB 000AA', 5000, 'Admin', NOW(), 'Admin', NOW(), 0);

    INSERT INTO CAR(CAR_BRAND, CAR_MODEL, CAR_TYPE, COLOR, CAPACITY, PLATE_NUMBER, MILEAGE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION) VALUES
    ('BMW', 'BMW 650', 'LCAR', 'BLACK', 5, 'YB 001AA', 6000, 'Admin', NOW(), 'Admin', NOW(), 0);

    INSERT INTO CAR(CAR_BRAND, CAR_MODEL, CAR_TYPE, COLOR, CAPACITY, PLATE_NUMBER, MILEAGE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION) VALUES
    ('Toyota', 'Toyota Camry', 'ECAR', 'SILVER', 5, 'YB 002AA', 7000, 'Admin', NOW(), 'Admin', NOW(), 0);

    INSERT INTO CAR(CAR_BRAND, CAR_MODEL, CAR_TYPE, COLOR, CAPACITY, PLATE_NUMBER, MILEAGE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION) VALUES
    ('Toyota', 'Toyota Camry', 'ECAR', 'GRAY', 5, 'YB 003AA', 8000, 'Admin', NOW(), 'Admin', NOW(), 0);


    INSERT INTO CAR_PRICE(CAR_ID, DATE_OF_YEAR, PRICE, IS_AVAILABLE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    SELECT  c.ID, dt.doy,dt.price,1,'Admin',NOW(),'Admin',NOW(),0
    FROM
        (SELECT @d:=(@d + interval 1 day) doy, @price:=@price+1 AS price
         FROM (SELECT @d:=date(NOW()), @price:=300) r
                  CROSS JOIN information_schema.tables t
         WHERE @d < DATE_ADD(NOW(), INTERVAL 89 DAY)
        ) dt
            CROSS JOIN CAR c
    WHERE c.PLATE_NUMBER = 'YB 000AA';

    INSERT INTO CAR_PRICE(CAR_ID, DATE_OF_YEAR, PRICE, IS_AVAILABLE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    SELECT  c.ID, dt.doy,dt.price,1,'Admin',NOW(),'Admin',NOW(),0
    FROM
        (SELECT @d:=(@d + interval 1 day) doy, @price:=@price+1 AS price
         FROM (SELECT @d:=date(NOW()), @price:=280) r
                  CROSS JOIN information_schema.tables t
         WHERE @d < DATE_ADD(NOW(), INTERVAL 89 DAY)
        ) dt
            CROSS JOIN CAR c
    WHERE c.PLATE_NUMBER = 'YB 001AA';

    INSERT INTO CAR_PRICE(CAR_ID, DATE_OF_YEAR, PRICE, IS_AVAILABLE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    SELECT  c.ID, dt.doy,dt.price,1,'Admin',NOW(),'Admin',NOW(),0
    FROM
        (SELECT @d:=(@d + interval 1 day) doy, @price:=@price+1 AS price
         FROM (SELECT @d:=date(NOW()), @price:=260) r
                  CROSS JOIN information_schema.tables t
         WHERE @d < DATE_ADD(NOW(), INTERVAL 89 DAY)
        ) dt
            CROSS JOIN CAR c
    WHERE c.PLATE_NUMBER = 'YB 002AA';

    INSERT INTO CAR_PRICE(CAR_ID, DATE_OF_YEAR, PRICE, IS_AVAILABLE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, VERSION)
    SELECT  c.ID, dt.doy,dt.price,1,'Admin',NOW(),'Admin',NOW(),0
    FROM
        (SELECT @d:=(@d + interval 1 day) doy, @price:=@price+1 AS price
         FROM (SELECT @d:=date(NOW()), @price:=240) r
                  CROSS JOIN information_schema.tables t
         WHERE @d < DATE_ADD(NOW(), INTERVAL 89 DAY)
        ) dt
            CROSS JOIN CAR c
    WHERE c.PLATE_NUMBER = 'YB 003AA';