CREATE DATABASE IF NOT EXISTS car_rental CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'carRental'@'localhost' IDENTIFIED BY '4XJyBEY75Hx4p6Hc';
GRANT ALL PRIVILEGES ON * . * TO 'carRental'@'localhost';

CREATE TABLE USERS(
      ID BIGINT NOT NULL AUTO_INCREMENT,
      USER_NAME VARCHAR(50) NOT NULL,
      PASSWORD VARCHAR(200) NOT NULL,
      FIRST_NAME VARCHAR(25),
      LAST_NAME VARCHAR(25),
      EMAIL VARCHAR(255) NOT NULL,
      PHONE VARCHAR(20) NOT NULL,
      DRIVING_LICENCE_NO VARCHAR(255) NOT NULL,

      CREATED_BY VARCHAR(50) NOT NULL,
      CREATED_DATE DATETIME NOT NULL,
      MODIFIED_BY VARCHAR(50) NOT NULL,
      MODIFIED_DATE DATETIME NOT NULL,
      VERSION BIGINT NOT NULL,
      PRIMARY KEY (ID),
      CONSTRAINT UC_USERNAME UNIQUE(USER_NAME)
);

CREATE TABLE CAR (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CAR_BRAND VARCHAR(20) NOT NULL, -- BMW, TOYOTA, ...
	CAR_MODEL VARCHAR(20) NOT NULL, -- BMW 650, ...
	CAR_TYPE VARCHAR(20) NOT NULL, -- SUV, VAN, FULL SIZE, ....
	COLOR VARCHAR(20) NOT NULL,
    CAPACITY TINYINT NOT NULL, -- 5, 7, 8 , 2
    PLATE_NUMBER VARCHAR(12) NOT NULL,
	MILEAGE INT NOT NULL,

	CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    MODIFIED_BY VARCHAR(50) NOT NULL,
    MODIFIED_DATE DATETIME NOT NULL,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UC_CAR_PLATE_NUMBER UNIQUE(PLATE_NUMBER)
);

CREATE TABLE CAR_PRICE(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   CAR_ID BIGINT NOT NULL,
   DATE_OF_YEAR DATE NOT NULL, -- 2020-10-21
   PRICE DECIMAL(6,2) NOT NULL, -- 328
   IS_AVAILABLE BIT NOT NULL, -- 0/1

   CREATED_BY VARCHAR(50) NOT NULL,
   CREATED_DATE DATETIME NOT NULL,
   MODIFIED_BY VARCHAR(50) NOT NULL,
   MODIFIED_DATE DATETIME NOT NULL,
   VERSION BIGINT NOT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT UC_CAR_DAY_PRICE UNIQUE(CAR_ID, DATE_OF_YEAR),
   CONSTRAINT FK_CAR_PRICE_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
);

CREATE TABLE RESERVATION_ORDER(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CAR_ID BIGINT NOT NULL,
	RESERVED_BY BIGINT NOT NULL, -- customer ID
	RESERVED_DATE DATETIME NOT NULL,
	PICK_UP_DATE DATE NOT NULL,
	PICK_UP_TIME TIME NOT NULL,
	RETURN_DATE DATE NOT NULL,
	RETURN_TIME TIME NOT NULL,
	TOTAL_AMOUNT DECIMAL(12,2) NOT NULL, -- SUM(price of every day of the rent range)
    RESERVE_STATUS TINYINT NOT NULL, -- Confirmed, Cancelled, Completed
    
	CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    MODIFIED_BY VARCHAR(50) NOT NULL,
    MODIFIED_DATE DATETIME NOT NULL,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RESERVATION_ORDER_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID),
    CONSTRAINT FK_RESERVATION_ORDER_USERS FOREIGN KEY (RESERVED_BY) REFERENCES USERS(ID)
);

